local Counter = require("utils.Counter")
describe("Counter", function()
  it("should count string", function()
    local c = Counter("aaabbc")
    assert.are.same({ key = "a", amount = 3 }, c:most_common()[1])
  end)
  it("should count lists", function()
    local c = Counter({ 1, 2, 1, 5, 1, 5, 3 })
    assert.are.same({ [1] = { key = 1, amount = 3 }, [2] = { key = 5, amount = 2 } }, c:most_common(2))

    local str_c = Counter({ "test", "test", "abc", "hej", "abc", "test" })
    assert.are.same({
      [1] = { key = "test", amount = 3 }, [2] = { key = "abc", amount = 2 } }, str_c:most_common(2)
    )
  end)
end)
