local Queue = require "utils.Queue"
describe("Queue",function ()
  it("should be able to push and pop queue",function ()
    local queue = Queue()
    queue:push(1)
    queue:push(42)
    assert.are(2, queue:size())
    assert.are.equal(1,queue:pop())
    assert.are(1, queue:size())
    assert.are.equal(42, queue:top())
    assert.are.equal(42, queue:pop())
    assert.are.equal(nil, queue:pop())
  end)
end)
